### ISSUE TITLE
I have an idea for your mod... :)

### ISSUE THREAD

**Issue by aigiz010** [brotazoa/Alloygery#12]
![image](https://user-images.githubusercontent.com/50463799/152687232-5ebc9676-95b9-4041-9f79-1c8bd5745811.png)
The additional stats that the equipment will give will depend on the potential...

**Comment by brotazoa** [comment]
Can you elaborate?

**Comment by aigiz010** [comment]
Equipment can be reforged using the material from which it is crafted (or something else) to try to increase the rank.

For example, you can make different improvements (which may have different levels (from 1 to 10)), these improvements can be attached to equipment. 
Equipment rank from F to Z will have from 1 to 10 (respectively) maximum improvements (quantity).
Different upgrades (types (e.g. diamond, emerald, etc.)) will have a different effect on the player after being applied to the equipment.
You can also make improvements that require a certain rank from the equipment (for example, creative flight from the S rank). But it will not be easy to make this stone either.

It will depend on the potential how strong the effect of improvement will be.

**Comment by brotazoa** [comment]
This reminds me of Draylar1's Tiered (https://www.curseforge.com/minecraft/mc-mods/tiered)

**Comment by brotazoa** [comment]
@aigiz010 You should join the Discord so we can talk more about the ideas you have: https://discord.gg/W5yXwW8yAA

**Comment by brotazoa** [comment]
I am going to close this, now that the discussion is on the discord.
