### ISSUE TITLE
List of metal tiers and alloys

### ISSUE THREAD

**Issue by Kira076** [brotazoa/Alloygery#16]
There used to be a list of the tiers for metals/materials on the mod's page (I believe along with what the alloys were? Or some other bit of information in a separate spoiler)... That seems to be removed and the only way I can see of working out which material is the next for progression is to search by the mod name in REI and check the order the tools appear in... Could there be a mod book, or even just the list on the mod page again, that explains this?

**Comment by brotazoa** [comment]
As a quick fix to this, I added the spoiler lists back to the mod page, but I will work on a more sophisticated solution like a guide book or similar.

**Comment by brotazoa** [comment]
I added a guide book via Patchouli which covers all the materials and upgrades. Closing this issue.
