### ISSUE TITLE
alloygery-2.0+1.18.2.jar - Unable to break iron ore with stone and gold pickaxe

### ISSUE THREAD

**Issue by Elderweiss-was-taken** [brotazoa/Alloygery#20]
Unable to break iron ore with stone and gold pickaxe

I am able to break iron ore with iron pickaxe and superior (diamond, netherite)

**Comment by brotazoa** [comment]
Not being able to mine iron ore with a gold pickaxe is a vanilla feature. 

Alloygery requires you to have a bronze pickaxe or better to mine iron ore.
