### ISSUE TITLE
Handles give more stat bonus than they should

### ISSUE THREAD

**Issue by mastery3** [brotazoa/Alloygery#22]
Example: Iron Handles should give 1.1x durability, 0.9x attack damage, and 1.1x attack speed compared to Wooden Handles. However, on testing, it appears to give 2.1x durability, 1.9x attack damage (relative to the "more info" attack damage), and +1 attack speed (despite the bonus supposedly being multiplicative, same with Invar Sword Blade & Guard) crafted with Iron Sword Blade & Guard.

**Comment by brotazoa** [comment]
What version? 1.18.2 or 1.19.2?

**Comment by mastery3** [comment]
1.19.2
