### ISSUE TITLE
Compat recipes should be placed into a recipes folder, not directly into the data folder

### ISSUE THREAD

**Issue by Nataly171** [brotazoa/Alloygery#24]
When the mod generates recipes for compatibility, such as for Create, those generated recipes are put directly into the "data" filepath, rather than a "recipes" filepath. This is inconsistent with vanilla Minecraft as well as every other mod, and makes working with the data unnecessarily difficult.

For this example, the recipe id should be "alloygery:recipes/compacting/copper_double_ingot"
![image](https://user-images.githubusercontent.com/109003930/232187099-643f8130-7744-4fef-9648-799c375cf16a.png)

**Comment by brotazoa** [comment]
All of Alloygery's recipes, as well as compatibility recipes, all exist within the recipes sub path. When viewing the recipe ID with EMI (as shown in your screenshot) "data/namespace/recipes/" is not included in the path.

Take the following vanilla crafting recipe as example:
![Screenshot from 2023-04-15 18-06-02](https://user-images.githubusercontent.com/14895001/232255260-fc8b183f-160f-403d-8841-728202fab52b.png)

Notice the recipe ID is not minecraft:recipes/copper_block

**Comment by Nataly171** [comment]
You are correct, idk how I missed that lol
