### ISSUE TITLE
[1.18.1] REI view of mod contents all mixed up

### ISSUE THREAD

**Issue by kwpugh** [brotazoa/Alloygery#4]
This may be related to the REI plugin issue, but may be not.

See pic below.

![Screen Shot 2022-01-28 at 12 00 42 PM](https://user-images.githubusercontent.com/8809210/151598372-8895eecb-ed4c-46e7-8dda-f712043f765e.png)

**Comment by brotazoa** [comment]
If the problem persists, please reopen this issue.

**Comment by kwpugh** [comment]
Much better.  Thanks

![Screen Shot 2022-01-28 at 9 03 55 PM](https://user-images.githubusercontent.com/8809210/151644911-3cec7931-af13-45c6-ad7f-e59e145de9b8.png)

**Comment by kwpugh** [comment]
Nice job with the textures by the way.

**Comment by brotazoa** [comment]
Thanks! I think that the ore textures are garbage, but I am happy with most everything else. Some of the tool textures need some work, but I am not an pixel artist, so I think this is the best I can do. lol

**Comment by kwpugh** [comment]
Same here, I'm awful at textures.

Iy you need to chat about coding, feel free to join my discord, I have a mod dev channel:  https://discord.gg/5tTC6VeJ
