### ISSUE TITLE
ru_ru.lang The Configuration Update

### ISSUE THREAD

**Issue by aigiz010** [brotazoa/Alloygery#7]
[ru_ru.zip](https://github.com/brotazoa/Alloygery/files/7963750/ru_ru.zip)
I didn't find where to write the translation: 
![image](https://user-images.githubusercontent.com/50463799/151662642-d452aaa4-ae01-4788-b633-f0015ab7a503.png) (Генерация руды)
![image](https://user-images.githubusercontent.com/50463799/151662736-c3938409-6f41-42f4-ace7-3f5481c8206a.png) (Средний размер скопления руды)
![image](https://user-images.githubusercontent.com/50463799/151662773-6ef1d9fc-913a-4a0e-85ec-843086d4115b.png) (Среднее количество скоплений руды в чанке)

**Comment by brotazoa** [comment]
Cloth-Config doesn't have localization for those tooltips unfortunately. Those are the comments in the json file. I will look into a way to have comments in the file without making those tooltips.

**Comment by aigiz010** [comment]
> 

don't worry, it's not necessary

**Comment by brotazoa** [comment]
I disabled the tooltips, they are not really needed. I am fixing a few other things related to fabric's resource load conditions, and will include your lang file in that update. Thank again for doing the translation, it is really appreciated!
