### ISSUE TITLE
ru_ru.lang update

### ISSUE THREAD

**Issue by aigiz010** [brotazoa/Alloygery#9]
[ru_ru.zip](https://github.com/brotazoa/Alloygery/files/7965278/ru_ru.zip)

**Comment by aigiz010** [comment]
it is not necessary to update the mod just for the sake of a small translation :)

**Comment by brotazoa** [comment]
I think it is really cool that you are even doing it!

**Comment by aigiz010** [comment]
consider it my hobby

**Comment by brotazoa** [comment]
Updated ru_ru translation included in latest release
